# Generated by Django 4.2.11 on 2024-04-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_calibration_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='expiration',
            field=models.CharField(max_length=30),
        ),
    ]
