# Generated by Django 4.2.11 on 2024-04-06 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_calibration_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='api.equipment'),
        ),
    ]
