# Generated by Django 4.2.11 on 2024-04-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_serviceorder_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='equipment',
            field=models.CharField(max_length=30),
        ),
    ]
