# Generated by Django 4.2.11 on 2024-04-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_calibration_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibration',
            name='equipment',
        ),
    ]
