# Generated by Django 4.2.11 on 2024-04-07 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_calibration_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='equipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='api.equipment'),
            preserve_default=False,
        ),
    ]
