# Generated by Django 4.2.11 on 2024-04-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_calibration_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='equipment',
            field=models.CharField(max_length=30),
        ),
    ]
