# Generated by Django 4.2.11 on 2024-04-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_calibration_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='equipment',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='executor',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='expiration',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calibration',
            name='service_type',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
