# Generated by Django 4.2.11 on 2024-04-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_calibration_equipment_calibration_executor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibration',
            name='service_type',
        ),
    ]
