# Generated by Django 4.2.11 on 2024-04-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_calibration_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='equip_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
