# Generated by Django 4.2.11 on 2024-04-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_calibration_equip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='equip_id',
            field=models.CharField(max_length=300),
        ),
    ]
