# Generated by Django 4.2.11 on 2024-04-07 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_calibration_equip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
