# Generated by Django 4.2.11 on 2024-04-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_calibration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='equip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration', to='api.equipment'),
        ),
    ]
