# Generated by Django 4.2.11 on 2024-04-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_calibration_equip_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='equipment',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='equip_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.equipment'),
            preserve_default=False,
        ),
    ]
