# Generated by Django 4.2.11 on 2024-04-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_serviceorder_equipment_serviceorder_equip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='closed_at',
            field=models.CharField(max_length=30),
        ),
    ]
