# Generated by Django 4.2.11 on 2024-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_equipment_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='author',
            new_name='added_by',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='state',
            field=models.CharField(default='Ativo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibration',
            name='executor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='expiration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='requester',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='function',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matriculation',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='identification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='closed_at',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='executor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='issue_description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='priority',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='requester',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
