# Generated by Django 4.2.11 on 2024-04-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_author_equipment_added_by_serviceorder_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='executor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='requester',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='function',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='matriculation',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='identification',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owner',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='executor',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='priority',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='requester',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='service_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
