# Generated by Django 4.2.11 on 2024-04-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_calibration_executor_alter_calibration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
