# Generated by Django 4.2.11 on 2024-05-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_serviceorder_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='expiration',
            field=models.CharField(max_length=30),
        ),
    ]
