# Generated by Django 4.2.11 on 2024-06-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_calibration_equip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibration',
            old_name='equip_id',
            new_name='equip',
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='equip_id',
            new_name='equip',
        ),
    ]
