# Generated by Django 4.2.11 on 2024-06-26 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_equip_id_calibration_equip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.customuser'),
        ),
    ]
