# Generated by Django 4.2.11 on 2024-06-29 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_client_remove_customuser_age_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 8, 27, 25, 439112, tzinfo=datetime.timezone.utc)),
        ),
    ]
