# Generated by Django 4.2.11 on 2024-06-29 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='calibration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='closed_at',
            field=models.DateTimeField(),
        ),
    ]
