# Generated by Django 4.2.11 on 2024-06-29 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_client_name_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
