# Generated by Django 4.2.11 on 2024-06-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_serviceorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='executor',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
