# Generated by Django 4.2.11 on 2024-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_serviceorder_solution_alter_serviceorder_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='solution',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
