# Generated by Django 4.2.11 on 2024-07-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_serviceorder_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.equipment'),
        ),
    ]
